<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\TipoVia;

class TipoViaSeeder extends Seeder
{
    public function run()
    {
        $items = [
            'Via',
            'Viale',
            'Piazza',
            'Corso',
            'Largo',
            'Piazzale',
            'Vicolo',
            'Strada',
            'Circonvallazione',
            'Tangenziale',
            'Rotonda',
            'Galleria',
            'Lungomare',
            'Lungolago',
            'Lungofiume',
            'Lungotevere',
            'Lungarno',
            'Lungoparco',
            'Lungocanale',
            'Lungodora',
            'Lungostura',
            'Strada Statale',
            'Strada Provinciale',
            'Strada Regionale',
            'Strada Comunale',
            'Strada Vicinale',
            'Strada Poderale',
            'Strada Pedonale',
            'Strada Residenziale',
            'Strada Industriale',
            'Strada Agricola',
            'Strada di Servizio',
            'Contrada',
            'Borgo',
            'Borgata',
            'Rione',
            'Quartiere',
            'Salita',
            'Discesa',
            'Traversa',
            'Passaggio',
            'Passaggio Pedonale',
            'Belvedere',
            'Belvedere Panoramico',
            'Vico',
            'Allee',
            'Rampa',
            'Scalinata',
            'Scaletta',
            'Scarpata',
            'Sentiero',
            'Piazzetta',
            'Stradone',
            'Stradello',
            'Stradetta',
            'Tangenziale Est',
            'Tangenziale Ovest',
            'Tangenziale Nord',
            'Tangenziale Sud',
            'Zona Industriale',
            'Zona Artigianale',
            'Zona Commerciale',
            'Zona Residenziale',
            'Villaggio',
            'Area Portuale',
            'Area Industriale',
            'Area Logistica',
            'Area Mercatale',
            'Area Fieristica',
            'Fondamenta',
            'Corte',
            'Cascina',
            'Cortile',
            'Vicinale Comunale',
            'Vicinale Com.',
            'Vicinale Provinciale',
            'Vicinale Prov.',
            'Vicinale Regionale',
            'Vicinale Reg.',
            'Vicinale Privata',
            'Vicinale Priv.',
            'Viale Alberato',
            'Viale Centrale',
            'Viale di Accesso',
            'Via Pedonale',
            'Percorso Natura',
            'Passeggiata',
            'Passerella',
            'Pista Ciclabile',
            'Greenway',
            'Rotatoria',
            'Ingresso Parco',
            'Ingresso Porto',
            'Ingresso Fiera',
            'Largo Monumentale',
            'Piazzale Stazione',
            'Piazzale Aeroporto',
            'Piazzale Ospedale',
            'Piazzale Universita',
            'Piazza Mercato',
            'Piazza Duomo',
            'Piazza Garibaldi',
            'Piazza Municipio',
            'Piazza Liberta',
            'Via Nazionale',
            'Via Centrale',
            'Via Roma',
            'Via Milano',
            'Via Torino',
            'Via Firenze',
            'Via Napoli',
            'Via Venezia',
            'Via Palermo',
            'Via Genova',
            'Via Bologna',
            'Via Bari',
            'Via Cagliari',
            'Via Trento',
            'Via Bolzano',
            'Corso Italia',
            'Corso Francia',
            'Corso Vittorio',
            'Corso Garibaldi',
            'Corso Umberto',
            'Corso Europa',
            'Viale Europa',
            'Viale Italia',
            'Viale Francia',
            'Viale Austria',
            'Lungomare Nord',
            'Lungomare Sud',
            'Lungolago Ovest',
            'Lungolago Est',
            'Lungofiume Nord',
            'Lungofiume Sud',
            'Passeggiata Mare',
            'Passeggiata Fiume',
            'Belvedere Mare',
            'Belvedere Lago',
            'Belvedere Collina',
            'Salita al Castello',
            'Discesa al Porto',
            'Rampa Garage',
            'Accesso Pedonale',
            'Raccordo',
            'Diramazione',
            'Spartitraffico',
            'Cavalcavia',
            'Sottopasso',
            'Portici',
            'Riviera',
            'Argine',
            'Molo',
            'Darsena',
            'Poggio',
            'Colle',
        ];

        foreach ($items as $abbr) {
            TipoVia::updateOrCreate(
                ['abbr' => $abbr],
                [
                    'nome' => $abbr,
                    'descrizione' => $abbr,
                    'attivo' => true,
                ]
            );
        }
    }
}
