import { test, expect, BASE_URL } from '../Support/playwright.js';
import { readFile } from 'node:fs/promises';

test.use({headless:true});
test('Anteprime visibili da configurazione, elenco, Schedina e storico; zero e PDF', async ({page}) => {
  test.setTimeout(90000);
  await page.goto(`${BASE_URL}/login`);
  await page.getByLabel(/Nome di accesso o email/i).fill('tassa-anteprima');
  await page.getByLabel(/Password personale/i).fill('Password-tassa-fixture-123!');
  await page.getByRole('button', {name:/Entra/i}).click();
  await expect(page).not.toHaveURL(/\/login$/);
  const ids = await (await page.request.get(`${BASE_URL}/tassa-anteprima-ids.json`)).json();
  for (const [caso, totale] of [['prima', '0'], ['dopo', '0'], ['esente', '0'], ['limite', '0'], ['positivo', '4.5'], ['parziale', '3'], ['checkout', '0']]) {
    await page.goto(`${BASE_URL}/tassa_di_soggiorno?anno_fiscale=2027`);
    await page.locator('#tab-stampa').click();
    await page.locator('#anteprima-schedina').selectOption(`${BASE_URL}/schedine/${ids[caso]}/tassa/anteprima`);
    const popup = page.waitForEvent('popup');
    await page.getByRole('link', {name:'Anteprima ricevuta',exact:true}).click();
    const doc = await popup;
    await expect(doc.locator('#ricevuta-tassa-card')).toBeVisible();
    await expect(doc.locator('#ricevuta-tassa-card')).toHaveAttribute('data-anteprima','si');
    await expect(doc.locator('[data-tassa-totale]')).toHaveAttribute('data-tassa-totale',totale);
    await expect(doc.getByText('Anteprima del calcolo',{exact:true})).toBeVisible();
    await expect(doc.locator('.ricevuta-software')).toContainText('Tanggo Platform | Versione 2.0');
    if (['prima','dopo','checkout'].includes(caso)) await expect(doc.locator('.ricevuta-tabella')).toContainText('Soggiorno fuori dal periodo');
    else await expect(doc.locator('.ricevuta-tabella')).not.toContainText('Soggiorno fuori dal periodo');
    if (caso === 'limite') await expect(doc.locator('body')).toContainText('limite massimo raggiunto');
    await doc.evaluate(() => { window.print = () => { window.__stampaRichiesta = true; }; });
    await doc.getByRole('button',{name:'Stampa ricevuta',exact:true}).click();
    expect(await doc.evaluate(() => window.__stampaRichiesta)).toBe(true);
    await doc.emulateMedia({media:'print'});
    await expect(doc.locator('.no-print')).toBeHidden();
    await expect(doc.locator('.ricevuta-software')).toBeVisible();
    await doc.pdf({path:`/private/tmp/ids-anteprima-${caso}.pdf`,format:'A4',printBackground:true,preferCSSPageSize:true});
    expect((await readFile(`/private/tmp/ids-anteprima-${caso}.pdf`)).length).toBeGreaterThan(1000);
    await doc.close();
  }
  await page.goto(`${BASE_URL}/schedine`);
  const popupElenco = page.waitForEvent('popup');
  await page.locator(`a[href="${BASE_URL}/schedine/${ids.positivo}/tassa/anteprima"]`).click();
  const daElenco = await popupElenco;
  await expect(daElenco.locator('[data-tassa-totale]')).toHaveAttribute('data-tassa-totale','4.5');
  await daElenco.close();
  await page.goto(`${BASE_URL}/schedine/${ids.prima}/modifica`);
  await page.locator('#schedina-step-tassa').click();
  await expect(page.getByRole('link',{name:'Anteprima ricevuta',exact:true})).toHaveAttribute('href', `${BASE_URL}/schedine/${ids.prima}/tassa/anteprima`);
  await expect(page.locator('#schedina-step-tassa-pane')).not.toContainText('Configura prima la tassa');
  const popupSchedina = page.waitForEvent('popup');
  await page.getByRole('link',{name:'Anteprima ricevuta',exact:true}).click();
  const daSchedina = await popupSchedina;
  await daSchedina.waitForLoadState('domcontentloaded');
  await expect(daSchedina.locator('[data-tassa-totale]')).toHaveAttribute('data-tassa-totale','0');
  await daSchedina.close();
  const sconosciuto = await page.request.get(`${BASE_URL}/schedine/${ids.crossyear}/tassa/anteprima`);
  expect(sconosciuto.status()).toBe(422);
  await page.goto(`${BASE_URL}/schedine/${ids.crossyear}/tassa/anteprima`);
  await expect(page.getByRole('link',{name:'Configurazione fiscale',exact:true})).toBeVisible();
  await expect(page.locator('#ricevuta-tassa-card')).toHaveCount(0);
  await page.goto(`${BASE_URL}/tassa_di_soggiorno/rapporto?mese=6&anno=2026`);
  await expect(page.getByText('Export consolidati e versioni',{exact:true})).not.toBeVisible();
  const download = page.waitForEvent('download');
  await page.getByRole('button',{name:'Consolida e scarica CSV',exact:true}).click();
  await page.getByRole('button',{name:'Sì, salva',exact:true}).click();
  await page.getByRole('button',{name:'OK',exact:true}).click();
  await download;
  await page.goto(`${BASE_URL}/tassa_di_soggiorno/rapporto?mese=6&anno=2026`);
  await page.getByText('Export consolidati e versioni',{exact:true}).click();
  await page.getByRole('link',{name:/versione 1/}).click();
  const popupStorico = page.waitForEvent('popup');
  await page.getByRole('link',{name:`Anteprima storica · Schedina ${ids.esente}`,exact:true}).click();
  const storico = await popupStorico;
  await expect(storico.locator('[data-tassa-totale]')).toHaveAttribute('data-tassa-totale','0');
  await expect(storico.locator('body')).toContainText('Versione storica consolidata 1');
  await storico.close();
});
