<?php

return [
    'name' => 'scheda-cliente',
    'tables' => [
        'clienti',
        'tipo_cliente',
        'gruppi',
        'titolo',
        'tipo_documento',
        'rilasciato_da',
        'geo_nazioni',
        'geo_regioni',
        'geo_province',
        'geo_comuni',
        'geo_cap',
    ],
    'routes' => [
        'newcustomer',
        'customer.store',
        'customer.edit',
        'customer.update',
        'customer.destroy',
        'tipo_cliente.index',
        'tipo_cliente.store',
        'tipo_cliente.update',
        'tipo_cliente.destroy',
    ],
    'files' => [
        'app/Http/Controllers/CustomerController.php',
        'app/Http/Controllers/TipoClienteController.php',
        'app/Models/Customers.php',
        'app/Models/TipoCliente.php',
        'resources/views/customers/new.blade.php',
        'resources/views/customers/partials/scheda-cliente-form.blade.php',
        'resources/views/customers/partials/scheda-cliente-scripts.blade.php',
        'resources/views/customers/edit.blade.php',
        'resources/views/customers/list.blade.php',
        'resources/views/components/xx/scheda-cliente.blade.php',
        'resources/views/tipo_cliente/index.blade.php',
        'resources/views/components/geo/italia.blade.php',
        'resources/views/components/calendario.blade.php',
        'resources/js/ui/geo-italia.js',
        'resources/js/ui/calendario.js',
        'resources/js/ui/config-ux.js',
        'routes/web.php',
        'database/migrations/2024_11_13_125626_create_customers_table.php',
        'database/migrations/2026_02_27_000001_rename_customers_to_clienti.php',
        'database/migrations/2026_03_10_210000_create_tipo_cliente_table.php',
        'database/migrations/2026_03_10_230000_add_missing_fields_to_clienti_for_scheda_cliente.php',
        'database/seeders/TipoClienteSeeder.php',
    ],
];
